In [1]:
import numpy as np 

In [2]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[1,2,3]])
c=a+b
print(c)

[[2 4 6]
 [5 7 9]]


In [3]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[1,2,3]])
c=a*b
print(c)

[[ 1  4  9]
 [ 4 10 18]]


In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
a=input("Enter the String to sort words in Alphabetic Order:")
W = a.split()

for i in range(len(W)):
    W[i] = W[i].lower()
    W.sort()
W



Enter the String to sort words in Alphabetic Order: A c d g f q


['a', 'c', 'd', 'f', 'g', 'q']

In [6]:
s=input("Enter the string you want to remove the Punctuations:")
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for i in s:
    if i not in punc:
        print(i, end="")
    else:
        pass
        


Enter the string you want to remove the Punctuations:Hey! I am Good Dude Are you?
Hey I am Good Dude Are you